---

version: '3.3'
services:
  tickets-db:
    image: postgres:14.9
    container_name: tickets-db
    env_file: ${TICKETS_DB_ENVFILE}
    volumes:
      - "${TICKETS_DB_VOLUME:-/opt/volumes/postgres/tickets}:/var/lib/postgresql/data"
    ports:
      - '5433:5432'

  tickets:
    build:
      context: ./
    image: rcs/tickets
    container_name: tickets
    depends_on:
      - tickets-db
    env_file: ${TICKETS_ENVFILE}
    ports:
      - '8200:8000'

